name: 'Respond To Issue Based on Label'
description: 'Act on issues when specific labels are added.'
inputs:
  configuration-path:
    description: 'The path for the label response configurations'
    default: '.github/respond-to-issue-based-on-label.yml'
  perform:
    description: 'Whether to perform any action, if needed. Set to false to do a dry-run.'
    default: true
  repo-token:
    description: 'The GITHUB_TOKEN secret.'
    required: true
runs:
  using: 'node12'
  main: 'lib/respond-to-issue-based-on-label.js'
branding:
  icon: 'bookmark'
  color: 'blue'
