name: Respond to Issues Based on Label
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled

jobs:
  processLabel:
    name: Process Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Process Label
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
